import { humanTime } from '@/common/human-time';

type ImagesProps = {
  images: string[];
  prompt: string;
  timeTaken: number;
  numberOfImages: number;
};

export const Images = ({ images, prompt, timeTaken, numberOfImages }: ImagesProps) => {
  return (
    <div className="flex flex-col gap-2">
      <div className="flex flex-row gap-2 flex-wrap overflow-x-scroll w-full">
        {/* The images generated by the prompt */}
        {images.map((image, index) => (
          // eslint-disable-next-line @next/next/no-img-element
          <img key={index} src={image} alt={prompt} className="size-56" />
        ))}
      </div>

      {/* Prompt */}
      <div>
        Generated {images.length}/{numberOfImages} image{images.length !== 1 && 's'} in {humanTime(timeTaken)} using the
        prompt &quot;{prompt}
        &quot;
      </div>
    </div>
  );
};
